# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Posgrado en Ciencias de la Sostenibilidad"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Posgrado en Ciencias de la Sostenibilidad, Unidad de Posgrado Edificio D primer piso
  Ciudad Universitaria
  CDMX
  Teléfono 5623-7012. Atención de lunes a viernes de 9:00 a 13:00 hrs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: Sostenibilidad_
# facebook_username: cienciasdelasostenibilidadunam
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# menu:
#   Coordinación:
#     - Acerca del posgrado: "/programa/introduccion"
#     - Recomendaciones para proyectos: "/programa/recomendaciones_proyectos"
#     - Directorio: "/programa/directorio"
#     - Calendario de actividades: "/programa/calendario"
#     - Calendario escolar: "/programa/calendario_escolar"
#     - Entidades: "/programa/entidades"
#     - Ubicación: "/programa/ubicacion"
#   Maestría:
#     - Plan de estudios: "/maestria/plan"
#     - Normas operativas: "/maestria/normas"
#     - Campos de conocimiento: "/maestria/campos"
#     - Mapa curricular: "/maestria/mapa"
#     - Cursos: "/maestria/cursos"
#     - Seminario de tesis: "/maestria/seminario_tesis/"
#     - Temas selectos: "/maestria/temas_selectos"
#     - Modalidades para la graduación: "/maestria/modalidades_graduacion"
#     - Graduación: "/maestria/graduacion"
#     - Descargables: "/maestria/descargables"
#   Doctorado:
#     - Plan de estudios: "/doctorado/plan"
#     - Normas operativas: "/doctorado/normas"
#     - Líneas de investigación: "/doctorado/lineas"
#     - Actividades académicas complementarias: "/doctorado/actividades"
#     - Candidatura: "/doctorado/candidatura"
#     - Descargables: "/doctorado/descargables"
#   Tutores y profesores:
#     - Acreditación de tutores
#     - Convocatoria Cursos
#     - Tutores acreditados
#     - Descargables
#   Becas y apoyos:
#     - Apoyos PAEP: "/apoyos/paep"
#     - Becas CONACYT: "/apoyos/beca_conacyt"
#     - Estímulo a la graduación: "/apoyos/estimulo_graduacion"
#   Comité Académico:
#     - Integrantes: "/comite/integrantes"
#     - Calendario de sesiones: "/comite/calendario"
#     - Acuerdos: "/comite/acuerdos"